/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosordenamientointerfaz;

import java.awt.Button;
import javax.swing.JOptionPane;

/**
 *
 * @author JOVA
 */
public class InternalFormColas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalForm
     */
    Burbujasimple bs = new Burbujasimple();
    public InternalFormColas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbNumber = new javax.swing.JLabel();
        txtArray = new javax.swing.JTextField();
        cmdClean = new javax.swing.JButton();
        cmdOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lbTittle = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Métodos de Ordenamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.gray));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNumber.setText("Números :");

        txtArray.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtArrayInputMethodTextChanged(evt);
            }
        });
        txtArray.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArrayKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArrayKeyTyped(evt);
            }
        });

        cmdClean.setText("Limpiar");
        cmdClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCleanActionPerformed(evt);
            }
        });

        cmdOrder.setText("Ordenar");
        cmdOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdClean, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdClean)
                    .addComponent(cmdOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtResult.setColumns(15);
        txtResult.setRows(3);
        jScrollPane1.setViewportView(txtResult);

        jLabel3.setText("Salida :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        lbTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTittle.setAlignmentX(1.5F);
        lbTittle.setAlignmentY(1.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOrderActionPerformed
        String texto = txtArray.getText();
        texto=texto.replaceAll(" ", "");
        if(texto.isEmpty()){
            JOptionPane.showMessageDialog(this,"Deebe de ingresar mínimo dos valores ");
        }else{
            
          int numeros[] = getArrayInt(txtArray.getText().split(","));
        String metodo = lbTittle.getText();
        switch(metodo){
            case "Colas":
                txtResult.setText(new Colas().ordenarA(numeros)); 
                break;
            case "Pilas":
                txtResult.setText(new Pilas().ordenarA(numeros)); 
                break;
            case "Programa 1":
                String search = JOptionPane.showInputDialog(this, "Que número deseas buscar");
                int index = Integer.parseInt(search);
                txtResult.setText(new Prog1().ordenar(numeros,index));
                break;
            case "Programa 2":
                String search1 = JOptionPane.showInputDialog(this, "Que número deseas buscar");
                int index1 = Integer.parseInt(search1);
                txtResult.setText(new Prog2().ordenar(numeros,index1)); 
                break;
            case "Programa 3":                
                txtResult.setText(new Prog3().ordenar()); 
                break;
            case "Programa 4":
                txtResult.setText(new Prog4().ordenar());
                    
        }  
        }
        
        //JOptionPane.showMessageDialog(this, metodo);
    }//GEN-LAST:event_cmdOrderActionPerformed
    public int[] getArrayInt(String array[]) {
        int arrayInt[] = new int[array.length];
        for (int i = 0; i < array.length; i++){
            arrayInt[i] = Integer.parseInt(array[i]);
        }
        return arrayInt;
    }    
    private void txtArrayInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtArrayInputMethodTextChanged
        
    }//GEN-LAST:event_txtArrayInputMethodTextChanged

    private void txtArrayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArrayKeyTyped
        /* c=evt.getKeyChar();
          if(Character.isLetter(c)) { 
              getToolkit().beep();
              evt.consume();
              JOptionPane.showMessageDialog(this, "Solo se aceptan números"); 
          } */
    }//GEN-LAST:event_txtArrayKeyTyped

    private void txtArrayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArrayKeyPressed
        // TODO add your handling code here:
            String texto = txtArray.getText();
            if(texto.split(" ").length > 0){
                eliminarEspaciosTexto();
            }
        
    }//GEN-LAST:event_txtArrayKeyPressed

    private void cmdCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCleanActionPerformed
       txtArray.setText("");
       txtResult.setText("");
       //txtLenght.grabFocus();
    }//GEN-LAST:event_cmdCleanActionPerformed

    
    private void eliminarEspaciosTexto(){
        String texto = txtArray.getText();
        txtArray.setText(texto.replaceAll(" ", ""));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClean;
    private javax.swing.JButton cmdOrder;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNumber;
    public javax.swing.JLabel lbTittle;
    private javax.swing.JTextField txtArray;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
